Repository frc5024/lib5k, pull requests merged in 2020-10, with the labels that each got.

#58 Add new-programmer-friendly wrappers for state-space control
  asyncHAL/build.gradle
  autonomous/build.gradle
  build.gradle
  common_drive/build.gradle
  control_loops/build.gradle
  control_loops/src/main/java/io/github/frc5024/lib5k/control_loops/models/DCBrushedMotor.java
  control_loops/src/main/java/io/github/frc5024/lib5k/control_loops/statespace/util/easylqr/ArmMath.java
  control_loops/src/main/java/io/github/frc5024/lib5k/control_loops/statespace/util/easylqr/FlywheelMath.java
  control_loops/src/main/java/io/github/frc5024/lib5k/control_loops/statespace/wrappers/EncoderElevatorController.java
  control_loops/src/main/java/io/github/frc5024/lib5k/control_loops/statespace/wrappers/RangeFinderElevatorController.java
  control_loops/src/main/java/io/github/frc5024/lib5k/control_loops/statespace/wrappers/SimpleFlywheelController.java
  control_loops/src/main/java/io/github/frc5024/lib5k/control_loops/statespace/wrappers/SingleJointedArmController.java
  examples/build.gradle
  examples/src/main/java/io/github/frc5024/lib5k/examples/drivebase_simulation/subsystems/DriveTrain.java
  examples/src/main/java/io/github/frc5024/lib5k/examples/neo_flywheel/subsystems/Flywheel.java
  examples/src/main/java/io/github/frc5024/lib5k/examples/tbh_flywheel/subsystems/Flywheel.java
  gradle_utils/mavenrepos.gradle
  gradle_utils/projectjar.gradle
  hardware/build.gradle
  hardware/common/build.gradle
  hardware/ctre/build.gradle
  hardware/generic/build.gradle
  hardware/kauai/build.gradle
  hardware/limelight/build.gradle
  hardware/ni/build.gradle
  hardware/revrobotics/build.gradle
  libKontrol/build.gradle
  logging/build.gradle
  purepursuit/build.gradle
  settings.gradle
  statespace/build.gradle
  statespace/src/main/java/edu/wpi/first/wpilibj/controller/PeriodVariantController.java
  statespace/src/main/java/edu/wpi/first/wpilibj/controller/PeriodVariantLoop.java
  statespace/src/main/java/edu/wpi/first/wpilibj/controller/PeriodVariantObserver.java
  statespace/src/main/java/edu/wpi/first/wpilibj/controller/PeriodVariantObserverCoeffs.java
  statespace/src/main/java/edu/wpi/first/wpilibj/controller/PeriodVariantPlant.java
  statespace/src/main/java/edu/wpi/first/wpilibj/controller/PeriodVariantPlantCoeffs.java
  statespace/src/main/java/edu/wpi/first/wpilibj/controller/StateSpaceController.java
  statespace/src/main/java/edu/wpi/first/wpilibj/controller/StateSpaceControllerCoeffs.java
  statespace/src/main/java/edu/wpi/first/wpilibj/controller/StateSpaceLoop.java
  statespace/src/main/java/edu/wpi/first/wpilibj/controller/StateSpaceObserver.java
  statespace/src/main/java/edu/wpi/first/wpilibj/controller/StateSpaceObserverCoeffs.java
  statespace/src/main/java/edu/wpi/first/wpilibj/controller/StateSpacePlant.java
  statespace/src/main/java/edu/wpi/first/wpilibj/controller/StateSpacePlantCoeffs.java
  telemetry/build.gradle
  templates/build.gradle
  utils/build.gradle
Labels: Needs testing, dependencies, documentation, enhancement

#81 Add a safe Notifier wrapper
  hardware/ni/build.gradle
  hardware/ni/src/main/java/io/github/frc5024/lib5k/hardware/ni/roborio/fpga/SafeNotifier.java
  hardware/ni/src/test/java/io/github/frc5024/lib5k/hardware/ni/roborio/fpga/SafeNotifierTest.java
Labels: documentation, enhancement, hacktoberfest

#97 Add a library loader script & do a lot of cleanup with vendordeps
  .github/workflows/build.yml
  .github/workflows/checkstyle.yml
  .github/workflows/docs.yml
  .gitignore
  build.gradle
  examples/build.gradle
  gradle/vendordeploader.gradle
  gradle5k/gradle5k.gradle
  lib5k/build.gradle
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/kauai/gyroscopes/NavX.java
  vendordeps/Phoenix.json
  vendordeps/REVRobotics.json
  vendordeps/navx_frc.json
Labels: dependencies, documentation, enhancement

#98 Merge the wiki with the main repo
  .github/workflows/docs.yml
  .gitignore
  docs/Gemfile
  docs/Gemfile.lock
  docs/README.md
  docs/_config.yml
  docs/installation/Compiling-Lib5K-From-Source.md
  docs/installation/Creating-a-Lib5K-Project.md
  docs/installation/README.md
  docs/technical/Multi-Threaded-Robot-Applications.md
  docs/technical/README.md
  docs/technical/The-5024-Coordinate-System.md
  docs/technical/The-Logging-System.md
  docs/technical/Troubleshooting.md
  docs/technical/Units-and-Measurements.md
  docs/tutorials/Building-a-State-Machine.md
  docs/tutorials/README.md
  docs/tutorials/Streaming-USB-Cameras-to-DriverStation.md
  lib5k/vendordeps/Phoenix.json
  lib5k/vendordeps/REVRobotics.json
  lib5k/vendordeps/navx_frc.json
Labels: documentation

#108 Update tutorial for setting up a Lib5K project
  README.md
  docs/installation/Creating-a-Lib5K-Project.md
  lib5k/build.gradle
Labels: documentation

#111 Document the FileManagement system
  .github/workflows/docs.yml
  docs/technical/Robot-Sessions.md
  docs/technical/The-Logging-System.md
  lib5k/build.gradle
Labels: documentation

#112 Fix a bug I made with JavaDoc generation
  lib5k/build.gradle
Labels: bug, documentation

#94 Add a Bezier Curve Autonomous Path
  lib5k/src/main/java/io/github/frc5024/purepursuit/pathgen/BezierPath.java
  lib5k/src/test/java/io/github/frc5024/purepursuit/pathgen/BezierPathTest.java
Labels: Experimental, enhancement

#114 Add documentation about Control Theory
  docs/technical/control/Introduction.md
  docs/technical/control/PID.md
  docs/technical/control/README.md
  docs/technical/control/State-Space.md
  examples/src/main/java/io/github/frc5024/lib5k/examples/autonomous_path_following/RobotConfig.java
  examples/src/main/java/io/github/frc5024/lib5k/examples/drivebase_simulation/RobotConfig.java
  examples/src/main/java/io/github/frc5024/lib5k/examples/tbh_flywheel/subsystems/Flywheel.java
  lib5k/src/main/java/ca/retrylife/frc/templates/turrets/ProfiledTurret.java
  lib5k/src/main/java/io/github/frc5024/common_drive/DriveTrainBase.java
  lib5k/src/main/java/io/github/frc5024/common_drive/DriveTrainConfig.java
  lib5k/src/main/java/io/github/frc5024/common_drive/controller/BaseController.java
  lib5k/src/main/java/io/github/frc5024/common_drive/controller/PDFController.java
  lib5k/src/main/java/io/github/frc5024/common_drive/controller/PDFGains.java
  lib5k/src/main/java/io/github/frc5024/common_drive/controller/PIFController.java
  lib5k/src/main/java/io/github/frc5024/common_drive/controller/PIFGains.java
  lib5k/src/main/java/io/github/frc5024/lib5k/control_loops/ExtendedPIDController.java
  lib5k/src/main/java/io/github/frc5024/lib5k/control_loops/PID.java
  lib5k/src/main/java/io/github/frc5024/lib5k/control_loops/PIDv2.java
  lib5k/src/main/java/io/github/frc5024/lib5k/control_loops/TBHController.java
  lib5k/src/main/java/io/github/frc5024/lib5k/control_loops/base/Controller.java
  lib5k/src/main/java/io/github/frc5024/lib5k/control_loops/base/ControllerBase.java
  lib5k/src/main/java/io/github/frc5024/lib5k/control_loops/base/SettlingController.java
  lib5k/src/main/java/io/github/frc5024/lib5k/control_loops/models/PIDProfile.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/generic/sensors/interfaces/IEncoderProvider.java
  lib5k/src/test/java/ca/retrylife/frc/templates/turrets/ProfiledTurretTest.java
  lib5k/src/test/java/io/github/frc5024/lib5k/control_loops/TestTBH.java
Labels: Needs testing, documentation, enhancement

#121 Begin work on system simulation tools
  .github/workflows/build.yml
  docs/technical/control/PID.md
  docs/technical/systems/Flywheel.md
  docs/technical/systems/README.md
  examples/src/main/java/io/github/frc5024/lib5k/examples/statespace_flywheel/Main.java
  examples/src/main/java/io/github/frc5024/lib5k/examples/statespace_flywheel/RobotConfig.java
  examples/src/main/java/io/github/frc5024/lib5k/examples/statespace_flywheel/subsystems/Flywheel.java
  lib5k/build.gradle
  lib5k/src/main/java/io/github/frc5024/lib5k/control_loops/models/DCBrushedMotor.java
  lib5k/src/main/java/io/github/frc5024/lib5k/control_loops/models/SystemCharacteristics.java
  lib5k/src/main/java/io/github/frc5024/lib5k/control_loops/statespace/StateSpaceSystem.java
  lib5k/src/main/java/io/github/frc5024/lib5k/control_loops/statespace/util/easylqr/ArmMath.java
  lib5k/src/main/java/io/github/frc5024/lib5k/control_loops/statespace/wrappers/EncoderElevatorController.java
  lib5k/src/main/java/io/github/frc5024/lib5k/control_loops/statespace/wrappers/RangeFinderElevatorController.java
  lib5k/src/main/java/io/github/frc5024/lib5k/control_loops/statespace/wrappers/SimpleFlywheelController.java
  lib5k/src/main/java/io/github/frc5024/lib5k/simulation/systems/ElevatorSystemSimulator.java
  lib5k/src/main/java/io/github/frc5024/lib5k/simulation/systems/FlywheelSystemSimulator.java
  lib5k/src/main/java/io/github/frc5024/lib5k/utils/RobotPresets.java
  lib5k/src/test/java/io/github/frc5024/lib5k/control_loops/ExtendedPIDControllerTest.java
  lib5k/src/test/java/io/github/frc5024/lib5k/control_loops/statespace/wrappers/RangeFinderElevatorControllerTest.java
  lib5k/src/test/java/io/github/frc5024/lib5k/control_loops/statespace/wrappers/SimpleFlywheelControllerTest.java
  lib5k/src/test/java/io/github/frc5024/lib5k/simulation/systems/ElevatorSystemSimulatorTest.java
  lib5k/src/test/java/io/github/frc5024/lib5k/simulation/systems/FlywheelSystemSimulatorTest.java
Labels: documentation, enhancement

#127 Document the required software for robot development
  docs/installation/Compiling-Lib5K-From-Source.md
  docs/installation/Creating-a-Lib5K-Project.md
  docs/installation/Creating-a-release.md
  docs/installation/Workspace-Setup.md
Labels: documentation

#123 Add a util for writing CSV data
  lib5k/src/main/java/io/github/frc5024/lib5k/bases/drivetrain/commands/PathFollowerCommand.java
  lib5k/src/main/java/io/github/frc5024/lib5k/logging/CSVFile.java
Labels: enhancement

#128 Expose RobotProgram's internal dashboard
  lib5k/src/main/java/io/github/frc5024/lib5k/autonomous/RobotProgram.java
Labels: enhancement

#131 Clean up DriveTrain implementations
  docs/technical/drivetrain/tankdrive.md
  examples/src/main/java/io/github/frc5024/lib5k/examples/autonomous_path_following/RobotConfig.java
  examples/src/main/java/io/github/frc5024/lib5k/examples/autonomous_path_following/subsystems/DriveTrain.java
  examples/src/main/java/io/github/frc5024/lib5k/examples/drivebase_simulation/RobotConfig.java
  examples/src/main/java/io/github/frc5024/lib5k/examples/drivebase_simulation/subsystems/DriveTrain.java
  examples/src/main/java/io/github/frc5024/lib5k/examples/teleop_drive/subsystems/DriveTrain.java
  lib5k/src/main/java/io/github/frc5024/lib5k/bases/drivetrain/AbstractDriveTrain.java
  lib5k/src/main/java/io/github/frc5024/lib5k/bases/drivetrain/commands/PathFollowerCommand.java
  lib5k/src/main/java/io/github/frc5024/lib5k/bases/drivetrain/implementations/DualPIDTankDriveTrain.java
  lib5k/src/main/java/io/github/frc5024/lib5k/bases/drivetrain/implementations/OpenLoopTankDriveTrain.java
  lib5k/src/main/java/io/github/frc5024/lib5k/bases/drivetrain/implementations/TankDriveTrain.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/common/sensors/interfaces/CommonEncoder.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/common/sensors/interfaces/ISimGyro.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/common/sensors/simulation/EncoderSimUtil.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/ctre/sensors/CANIfierEncoder.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/ctre/sensors/ExtendedCANCoder.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/ctre/sensors/ExtendedPigeonIMU.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/ctre/sensors/TalonEncoder.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/generic/gyroscopes/ADGyro.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/generic/motors/MockSpeedController.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/kauai/gyroscopes/NavX.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/revrobotics/sensors/SparkMaxEncoder.java
  lib5k/src/main/java/io/github/frc5024/purepursuit/PurePursuitController.java
  lib5k/src/test/java/io/github/frc5024/lib5k/bases/drivetrain/implementations/DualPIDTankDriveTrainTest.java
  lib5k/src/test/java/io/github/frc5024/lib5k/hardware/common/sensors/simulation/EncoderSimUtilTest.java
Labels: Needs testing, bug, documentation, enhancement

#136 Add unit tests for more base hardware types
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/generic/ledstrips/BlinkinDriver.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/generic/motors/LinearActuator.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/generic/pneumatics/LazySolenoid.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/generic/sensors/LineBreak.java
  lib5k/src/test/java/io/github/frc5024/lib5k/hardware/generic/ledstrips/BlinkinDriverTest.java
  lib5k/src/test/java/io/github/frc5024/lib5k/hardware/generic/motors/LinearActuatorTest.java
  lib5k/src/test/java/io/github/frc5024/lib5k/hardware/generic/pneumatics/LazySolenoidTest.java
  lib5k/src/test/java/io/github/frc5024/lib5k/hardware/generic/sensors/HallEffectTest.java
  lib5k/src/test/java/io/github/frc5024/lib5k/hardware/generic/sensors/LimitSwitchTest.java
  lib5k/src/test/java/io/github/frc5024/lib5k/hardware/generic/sensors/LineBreakTest.java
Labels: enhancement

#137 Make a large improvement to drivetrain unit testing
  lib5k/src/main/java/io/github/frc5024/lib5k/bases/drivetrain/implementations/DualPIDTankDriveTrain.java
  lib5k/src/main/java/io/github/frc5024/lib5k/bases/drivetrain/implementations/TankDriveTrain.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/common/sensors/simulation/EncoderSimUtil.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/ctre/sensors/CANIfierEncoder.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/ctre/sensors/ExtendedCANCoder.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/ctre/sensors/TalonEncoder.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/revrobotics/sensors/SparkMaxEncoder.java
  lib5k/src/main/java/io/github/frc5024/lib5k/utils/TimeScale.java
  lib5k/src/test/java/io/github/frc5024/lib5k/bases/drivetrain/implementations/DualPIDTankDriveTrainTest.java
  lib5k/src/test/java/io/github/frc5024/lib5k/hardware/common/sensors/simulation/EncoderSimUtilTest.java
Labels: enhancement

#139 Rewrite Limelight client code to better integrate with the library
  .vscode/settings.json
  docs/technical/Computer-Vision.md
  examples/src/main/java/io/github/frc5024/lib5k/examples/vision_align/Main.java
  examples/src/main/java/io/github/frc5024/lib5k/examples/vision_align/OI.java
  examples/src/main/java/io/github/frc5024/lib5k/examples/vision_align/README.md
  examples/src/main/java/io/github/frc5024/lib5k/examples/vision_align/RobotConfig.java
  examples/src/main/java/io/github/frc5024/lib5k/examples/vision_align/commands/DriveCommand.java
  examples/src/main/java/io/github/frc5024/lib5k/examples/vision_align/subsystems/DriveTrain.java
  examples/src/main/java/io/github/frc5024/lib5k/examples/vision_align/subsystems/Vision.java
  lib5k/src/main/java/ca/retrylife/frc/limelight/CameraTranslation.java
  lib5k/src/main/java/ca/retrylife/frc/limelight/Contour.java
  lib5k/src/main/java/ca/retrylife/frc/limelight/Crosshair.java
  lib5k/src/main/java/ca/retrylife/frc/limelight/Limelight.java
  lib5k/src/main/java/ca/retrylife/frc/limelight/Target.java
  lib5k/src/main/java/ca/retrylife/frc/limelight/util/NetworkTableUtil.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/limelightvision/BaseLimeLight.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/limelightvision/products/LimeLight1.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/limelightvision/products/LimeLight2.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/limelightvision/settings/LimeLightLEDMode.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/limelightvision/settings/LimeLightOperationMode.java
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/limelightvision/settings/LimeLightStreamMode.java
  lib5k/src/main/java/io/github/frc5024/lib5k/utils/FMSNetworking.java
  lib5k/src/main/java/io/github/frc5024/lib5k/vision/types/AxisAlignedBoundingBox.java
  lib5k/src/main/java/io/github/frc5024/lib5k/vision/types/Contour.java
  lib5k/src/main/java/io/github/frc5024/lib5k/vision/types/HyperbolicAxisAlignedBoundingBox.java
  lib5k/src/test/java/io/github/frc5024/lib5k/hardware/limelightvision/BaseLimeLightTest.java
  lib5k/src/test/java/io/github/frc5024/lib5k/vision/types/AxisAlignedBoundingBoxTest.java
  lib5k/src/test/java/io/github/frc5024/lib5k/vision/types/HyperbolicAxisAlignedBoundingBoxTest.java
Labels: documentation, enhancement

#140 Add past design documents
  docs/assets/pure_pursuit_lookahead1.png
  docs/assets/pure_pursuit_lookahead2.png
  docs/rfc/Pure-Pursuit.md
  docs/rfc/README.md
  docs/rfc/TankDriveTrain.md
Labels: documentation

#138 Unit test the PID controller
  lib5k/src/main/java/io/github/frc5024/lib5k/hardware/ni/roborio/fpga/FPGAClock.java
  lib5k/src/main/java/io/github/frc5024/lib5k/unittest/FakeScheduler.java
  lib5k/src/main/java/io/github/frc5024/lib5k/unittest/Grapher.java
  lib5k/src/main/java/io/github/frc5024/lib5k/utils/TimeScale.java
  lib5k/src/test/java/io/github/frc5024/lib5k/control_loops/ExtendedPIDControllerTest.java
  lib5k/src/test/java/io/github/frc5024/lib5k/unittest/GrapherTest.java
Labels: enhancement

#143 Add JSON config loading
  build.gradle
  docs/tutorials/JSON-Configs.md
  gradle/simpleunittest.gradle
  gradle5k/gradle5k.gradle
  lib5k/src/main/deploy/robotconfig.json
  lib5k/src/main/java/io/github/frc5024/lib5k/config/SingleInstanceJSONConfig.java
  lib5k/src/main/java/io/github/frc5024/lib5k/config/types/JSONEncoder.java
  lib5k/src/main/java/io/github/frc5024/lib5k/config/types/JSONMotor.java
  lib5k/src/main/java/io/github/frc5024/lib5k/config/types/JSONPIDGains.java
  lib5k/src/main/java/io/github/frc5024/lib5k/unittest/ConfigValidator.java
  lib5k/src/test/java/io/github/frc5024/lib5k/config/SingleInstanceJSONConfigTest.java
Labels: dependencies, documentation, enhancement
